"""Tests for calibration/calibrate_halos.py.

Only the pure/testable functions are covered:
  - _nearest: geometry — finds the closest point within a threshold
  - _save: I/O output format — verified via tmp file

main() and _draw_* and _handle_event require a pygame display and are
marked as integration-only. They are excluded from unit coverage.
"""

from __future__ import annotations

import math
import os

import pytest
from calibration.calibrate_halos import (
    FIRE_LABELS,
    MODE_FIRE,
    MODE_MUSH,
    R_FIRE_L,
    R_FIRE_M,
    R_FIRE_S,
    R_MUSH_L,
    R_MUSH_M,
    R_MUSH_S,
    _nearest,
    _save,
)

# ---------------------------------------------------------------------------
# _nearest — returns index of closest point within threshold
# ---------------------------------------------------------------------------


class TestNearest:
    def test_returns_index_of_closest_point(self):
        points = [(100, 100, 0), (200, 200, 0), (300, 300, 0)]
        idx = _nearest(points, 105, 105)
        assert idx == 0

    def test_returns_none_when_all_points_beyond_threshold(self):
        points = [(0, 0, 0), (500, 500, 0)]
        idx = _nearest(points, 250, 250, threshold=35)
        assert idx is None

    def test_returns_none_for_empty_list(self):
        idx = _nearest([], 100, 100)
        assert idx is None

    def test_respects_threshold(self):
        # Point is exactly at distance 36 — beyond default threshold of 35
        points = [(100 + 36, 100, 0)]
        idx = _nearest(points, 100, 100, threshold=35)
        assert idx is None

    def test_point_within_threshold_returned(self):
        # Point at distance 20 — within threshold of 35
        points = [(100 + 20, 100, 0)]
        idx = _nearest(points, 100, 100, threshold=35)
        assert idx == 0

    def test_returns_closest_among_multiple_candidates(self):
        # Both within threshold — should return the closer one
        points = [(110, 100, 0), (105, 100, 0)]  # distances: 10, 5
        idx = _nearest(points, 100, 100, threshold=35)
        assert idx == 1

    def test_works_with_fire_and_mush_combined_list(self):
        # Simulates the combined list used in _handle_event right-click
        fire = [(50, 50, 45), (200, 200, 28)]
        mush = [(300, 300, 22), (400, 400, 16)]
        all_pts = [(x, y, 0) for x, y, *_ in fire + mush]
        idx = _nearest(all_pts, 205, 200, threshold=35)
        assert idx == 1  # second fire point


# ---------------------------------------------------------------------------
# _save — writes BACKGROUND_LIGHTS and MUSHROOM_LIGHTS to a file
# ---------------------------------------------------------------------------


MUSH_CYAN = (70, 220, 200)
MUSH_RED = (220, 80, 60)


class TestSave:
    def test_writes_fire_halos_to_file(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)

        fire = [(100, 200, R_FIRE_L), (300, 400, R_FIRE_M)]
        _save(fire, [])

        output = (tmp_path / "scripts" / "calibration_result.py").read_text()
        assert "BACKGROUND_LIGHTS = [" in output
        assert "( 100,  200, 45)" in output
        assert "( 300,  400, 28)" in output
        assert "lantern" in output
        assert "window" in output

    def test_writes_mushroom_halos_to_file(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)

        mush = [(50, 60, R_MUSH_L, MUSH_CYAN), (70, 80, R_MUSH_M, MUSH_RED)]
        _save([], mush)

        output = (tmp_path / "scripts" / "calibration_result.py").read_text()
        assert "MUSHROOM_LIGHTS = [" in output
        assert "70, 220, 200" in output  # MUSH_CYAN color values
        assert "220,  80,  60" in output  # MUSH_RED color values

    def test_writes_both_sections_when_both_present(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)

        fire = [(100, 100, R_FIRE_S)]
        mush = [(200, 200, R_MUSH_S, MUSH_CYAN)]
        _save(fire, mush)

        output = (tmp_path / "scripts" / "calibration_result.py").read_text()
        assert "BACKGROUND_LIGHTS = [" in output
        assert "MUSHROOM_LIGHTS = [" in output

    def test_writes_empty_lists_when_no_halos(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)

        _save([], [])

        output = (tmp_path / "scripts" / "calibration_result.py").read_text()
        assert "BACKGROUND_LIGHTS = [" in output
        assert "MUSHROOM_LIGHTS = [" in output

    def test_output_starts_with_generated_comment(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)

        _save([], [])

        output = (tmp_path / "scripts" / "calibration_result.py").read_text()
        assert output.startswith("# Generated by")


# ---------------------------------------------------------------------------
# Constants — verify domain values are consistent
# ---------------------------------------------------------------------------


class TestConstants:
    def test_fire_radii_ordered_large_to_small(self):
        assert R_FIRE_L > R_FIRE_M > R_FIRE_S

    def test_mushroom_radii_ordered_large_to_small(self):
        assert R_MUSH_L > R_MUSH_M > R_MUSH_S

    def test_fire_labels_cover_all_radii(self):
        assert R_FIRE_L in FIRE_LABELS
        assert R_FIRE_M in FIRE_LABELS
        assert R_FIRE_S in FIRE_LABELS

    def test_mode_constants_are_distinct_strings(self):
        assert MODE_FIRE != MODE_MUSH
        assert isinstance(MODE_FIRE, str)
        assert isinstance(MODE_MUSH, str)


def test_tc003_no_prints_in_calibration():
    """TC-003: Check that print() calls are removed/replaced by logging in calibrate_halos.py."""
    from pathlib import Path

    script_path = Path(__file__).parents[3] / "tools" / "src" / "calibration" / "calibrate_halos.py"
    assert script_path.exists()

    content = script_path.read_text(encoding="utf-8")

    # Exclude normal comments and docstrings, look for active print statements
    import ast
    tree = ast.parse(content)

    prints = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "print":
            prints.append(node.lineno)

    assert not prints, f"Found print() call at lines {prints} in calibrate_halos.py. Use logging instead."


def test_tc004_no_french_comments_in_calibration():
    """TC-004: Ensure no French developer comments remain in calibrate_halos.py."""
    import re
    from pathlib import Path

    script_path = Path(__file__).parents[3] / "tools" / "src" / "calibration" / "calibrate_halos.py"
    assert script_path.exists()

    content = script_path.read_text(encoding="utf-8")

    # Look for common French words or accents in comments
    french_indicators = re.compile(r'#.*(?:lanterne|fenêtre|petite|champignon|rouge|petit)', re.IGNORECASE)
    matches = french_indicators.findall(content)
    assert not matches, f"Found French comments in calibrate_halos.py: {matches}"


# ---------------------------------------------------------------------------
# _handle_event — covers all keyboard/mouse branches (lines 134-180)
# ---------------------------------------------------------------------------


class _FakeEvent:
    """Minimal pygame.Event surrogate for unit tests."""
    def __init__(self, type_id: int, **attrs):
        self.type = type_id
        for k, v in attrs.items():
            setattr(self, k, v)


class _FakeMods:
    """Bit-field surrogate for pygame.key.get_mods()."""
    def __init__(self, shift=False, ctrl=False):
        from unittest.mock import MagicMock
        self._shift = shift
        self._ctrl = ctrl

    def __and__(self, flag):
        # pygame.KMOD_SHIFT = 1, pygame.KMOD_CTRL = 64 (typical values)
        # We return truthy/falsy based on what was requested
        try:
            import pygame
            if flag == pygame.KMOD_SHIFT:
                return 1 if self._shift else 0
            if flag == pygame.KMOD_CTRL:
                return 1 if self._ctrl else 0
        except Exception:
            pass
        return 0


class TestHandleEvent:
    """Tests for _handle_event covering all branches (lines 134-180)."""

    def _setup(self):
        from unittest.mock import MagicMock
        import pygame
        self.pygame = pygame
        self.fire_pts: list = []
        self.mush_pts: list = []
        self.mode = MODE_FIRE
        self.screen = MagicMock()
        return self

    def _call(self, event):
        from calibration.calibrate_halos import _handle_event
        import pygame
        return _handle_event(event, True, self.mode, self.fire_pts, self.mush_pts, self.screen)

    def test_quit_event_stops_running(self):
        import pygame
        self._setup()
        event = _FakeEvent(pygame.QUIT)
        running, mode, screen = self._call(event)
        assert running is False

    def test_escape_stops_running(self):
        import pygame
        self._setup()
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_ESCAPE)
        running, mode, _ = self._call(event)
        assert running is False

    def test_q_stops_running(self):
        import pygame
        self._setup()
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_q)
        running, _, _ = self._call(event)
        assert running is False

    def test_m_switches_mode_fire_to_mush(self):
        import pygame
        self._setup()
        self.mode = MODE_FIRE
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_m)
        _, mode, _ = self._call(event)
        assert mode == MODE_MUSH

    def test_m_switches_mode_mush_to_fire(self):
        import pygame
        self._setup()
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_m)
        _, mode, _ = self._call(event)
        assert mode == MODE_FIRE

    def test_z_undoes_last_fire_point(self):
        import pygame
        self._setup()
        self.fire_pts = [(100, 100, 45), (200, 200, 28)]
        self.mode = MODE_FIRE
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_z)
        self._call(event)
        assert len(self.fire_pts) == 1
        assert self.fire_pts[0] == (100, 100, 45)

    def test_z_undoes_last_mush_point(self):
        import pygame
        self._setup()
        self.mush_pts = [(100, 100, 22, (70, 220, 200))]
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_z)
        self._call(event)
        assert len(self.mush_pts) == 0

    def test_z_noop_when_fire_empty(self):
        import pygame
        self._setup()
        self.fire_pts = []
        self.mode = MODE_FIRE
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_z)
        self._call(event)  # must not raise
        assert len(self.fire_pts) == 0

    def test_z_noop_when_mush_empty(self):
        import pygame
        self._setup()
        self.mush_pts = []
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_z)
        self._call(event)  # must not raise

    def test_s_calls_save(self, tmp_path, monkeypatch):
        import pygame
        import os
        monkeypatch.chdir(tmp_path)
        os.makedirs("scripts", exist_ok=True)
        self._setup()
        self.fire_pts = [(10, 20, 45)]
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_s)
        self._call(event)
        assert (tmp_path / "scripts" / "calibration_result.py").exists()

    def test_left_click_fire_mode_large(self):
        import pygame
        from unittest.mock import patch, MagicMock
        self._setup()
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(300, 400))
        with patch("pygame.key.get_mods", return_value=0):
            self._call(event)
        assert len(self.fire_pts) == 1
        assert self.fire_pts[0][2] == R_FIRE_L

    def test_left_click_fire_mode_shift_medium(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(100, 200))
        with patch("pygame.key.get_mods", return_value=pygame.KMOD_SHIFT):
            self._call(event)
        assert len(self.fire_pts) == 1
        assert self.fire_pts[0][2] == R_FIRE_M

    def test_left_click_fire_mode_ctrl_small(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(100, 200))
        with patch("pygame.key.get_mods", return_value=pygame.KMOD_CTRL):
            self._call(event)
        assert len(self.fire_pts) == 1
        assert self.fire_pts[0][2] == R_FIRE_S

    def test_left_click_mush_mode_large(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(50, 60))
        with patch("pygame.key.get_mods", return_value=0):
            self._call(event)
        assert len(self.mush_pts) == 1
        assert self.mush_pts[0][2] == R_MUSH_L

    def test_left_click_mush_mode_shift_medium(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(50, 60))
        with patch("pygame.key.get_mods", return_value=pygame.KMOD_SHIFT):
            self._call(event)
        assert len(self.mush_pts) == 1
        assert self.mush_pts[0][2] == R_MUSH_M

    def test_left_click_mush_mode_ctrl_small(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.mode = MODE_MUSH
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=1, pos=(50, 60))
        with patch("pygame.key.get_mods", return_value=pygame.KMOD_CTRL):
            self._call(event)
        assert len(self.mush_pts) == 1
        assert self.mush_pts[0][2] == R_MUSH_S

    def test_right_click_removes_fire_point(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.fire_pts = [(100, 100, 45)]
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=3, pos=(100, 100))
        with patch("pygame.key.get_mods", return_value=0):
            self._call(event)
        assert len(self.fire_pts) == 0

    def test_right_click_removes_mush_point(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.mush_pts = [(200, 200, 22, (70, 220, 200))]
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=3, pos=(200, 200))
        with patch("pygame.key.get_mods", return_value=0):
            self._call(event)
        assert len(self.mush_pts) == 0

    def test_right_click_noop_when_no_nearby_point(self):
        import pygame
        from unittest.mock import patch
        self._setup()
        self.fire_pts = [(100, 100, 45)]
        event = _FakeEvent(pygame.MOUSEBUTTONDOWN, button=3, pos=(500, 500))
        with patch("pygame.key.get_mods", return_value=0):
            self._call(event)
        assert len(self.fire_pts) == 1  # unchanged

    def test_f_key_toggles_fullscreen(self):
        import pygame
        from unittest.mock import patch, MagicMock
        self._setup()
        fake_screen = MagicMock()
        event = _FakeEvent(pygame.KEYDOWN, key=pygame.K_f)
        with patch("pygame.display.set_mode", return_value=fake_screen) as mock_set:
            _, _, new_screen = self._call(event)
            mock_set.assert_called_once()
            assert new_screen is fake_screen


# ---------------------------------------------------------------------------
# _draw_legend / _draw_points — require pygame Surface (headless display)
# ---------------------------------------------------------------------------

import os
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")


class TestDrawLegend:
    """Tests for _draw_legend — covers lines 92-110."""

    def setup_method(self):
        import pygame
        pygame.init()
        self.screen = pygame.Surface((400, 200))
        self.font = pygame.font.SysFont("monospace", 14)

    def teardown_method(self):
        import pygame
        pygame.quit()

    def test_draw_legend_fire_mode_no_crash(self):
        from calibration.calibrate_halos import _draw_legend
        _draw_legend(self.screen, self.font, "FIRE", 3, 1)

    def test_draw_legend_mushroom_mode_no_crash(self):
        from calibration.calibrate_halos import _draw_legend
        _draw_legend(self.screen, self.font, "MUSHROOM", 0, 5)

    def test_draw_legend_zero_counts(self):
        from calibration.calibrate_halos import _draw_legend
        _draw_legend(self.screen, self.font, "FIRE", 0, 0)


class TestDrawPoints:
    """Tests for _draw_points — covers lines 113-131."""

    def setup_method(self):
        import pygame
        pygame.init()
        self.screen = pygame.Surface((800, 600))

    def teardown_method(self):
        import pygame
        pygame.quit()

    def test_draw_points_fire_only_no_crash(self):
        from calibration.calibrate_halos import _draw_points
        fire = [(100, 100, 45), (200, 200, 28), (300, 300, 18)]
        _draw_points(self.screen, fire, [])

    def test_draw_points_mush_only_no_crash(self):
        from calibration.calibrate_halos import _draw_points
        mush = [(150, 150, 22, (70, 220, 200)), (250, 250, 16, (220, 80, 60))]
        _draw_points(self.screen, [], mush)

    def test_draw_points_both_no_crash(self):
        from calibration.calibrate_halos import _draw_points
        fire = [(100, 100, 45)]
        mush = [(200, 200, 22, (70, 220, 200))]
        _draw_points(self.screen, fire, mush)

    def test_draw_points_empty_lists_no_crash(self):
        from calibration.calibrate_halos import _draw_points
        _draw_points(self.screen, [], [])

    def test_draw_points_unknown_radius_uses_fallback_color(self):
        """Fire point with radius not in FIRE_COLORS still draws (uses default)."""
        from calibration.calibrate_halos import _draw_points
        # Radius 99 is not in FIRE_COLORS dict → get() returns (255, 255, 255)
        fire = [(100, 100, 99)]
        _draw_points(self.screen, fire, [])  # must not raise
