"""
Halo Calibration Tool
=====================
Usage: python3 scripts/calibrate_halos.py

Controls:
  LEFT CLICK     → Add a LARGE halo (r=45) at cursor position
  SHIFT+CLICK    → Add a MEDIUM halo (r=28)
  CTRL+CLICK     → Add a SMALL halo (r=18)
  RIGHT CLICK    → Remove nearest halo within 35px
  Z              → Undo last added halo
  S              → Save result and sys.stdout.write constants
  F              → Toggle fullscreen/windowed
  Q / ESC        → Quit (auto-saves if there are points)

Visual:
  Red    circle = large (lantern r=45)
  Orange circle = medium (window r=28)
  Yellow circle = small (tiny window r=18)

The tool shows the ACTUAL background used by the game.
Coordinates are in pygame 1280×720 space — identical on all machines.
"""
import sys
import os
import math
import pygame

BG_PATH = os.path.join("assets", "images", "menu", "01-menu_background.png")
OUTPUT_PATH = os.path.join("scripts", "calibration_result.py")
SCREEN_W, SCREEN_H = 1280, 720

RADIUS_LARGE  = 45
RADIUS_MEDIUM = 28
RADIUS_SMALL  = 18

COLOR_LARGE  = (255,  60,  60)   # red
COLOR_MEDIUM = (255, 160,  30)   # orange
COLOR_SMALL  = (255, 240,  60)   # yellow


RADIUS_COLORS = {
    RADIUS_LARGE:  COLOR_LARGE,
    RADIUS_MEDIUM: COLOR_MEDIUM,
    RADIUS_SMALL:  COLOR_SMALL,
}


def _nearest(points: list, mx: int, my: int, threshold: int = 35) -> int | None:
    best_i, best_d = None, threshold
    for i, (x, y, _) in enumerate(points):
        d = math.hypot(x - mx, y - my)
        if d < best_d:
            best_i, best_d = i, d
    return best_i


def _save(points: list) -> None:
    lines = ["# Generated by scripts/calibrate_halos.py\n",
             "BACKGROUND_LIGHTS = [\n"]
    for x, y, r in points:
        label = "lanterne" if r == RADIUS_LARGE else ("fenêtre" if r == RADIUS_MEDIUM else "petite fenêtre")
        lines.append(f"    ({x:4d}, {y:4d}, {r:2d}),  # {label}\n")
    lines.append("]\n")
    with open(OUTPUT_PATH, "w") as f:
        f.writelines(lines)
    sys.stdout.write("\n".join(lines))
    sys.stdout.write(f"→ Saved to {OUTPUT_PATH}")


def main() -> None:
    pygame.init()
    # FULLSCREEN | SCALED: pygame étire le canvas 1280×720 sur tout l'écran physique
    # et traduit automatiquement les coords souris → espace logique 1280×720
    # identique à l'espace de rendu du jeu sur toutes les machines.
    screen = pygame.display.set_mode(
        (SCREEN_W, SCREEN_H), pygame.FULLSCREEN | pygame.SCALED
    )
    pygame.display.set_caption("Halo Calibration")
    fullscreen = True

    try:
        bg = pygame.image.load(BG_PATH).convert()
        bg = pygame.transform.smoothscale(bg, (SCREEN_W, SCREEN_H))
    except pygame.error as e:
        sys.stdout.write(f"Cannot load background: {e}")
        sys.exit(1)

    font = pygame.font.SysFont("monospace", 14)
    points: list[tuple[int, int, int]] = []
    clock = pygame.time.Clock()

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_ESCAPE, pygame.K_q):
                    running = False
                elif event.key == pygame.K_z and points:
                    points.pop()
                elif event.key == pygame.K_s:
                    _save(points)
                elif event.key == pygame.K_f:
                    fullscreen = not fullscreen
                    flag = (pygame.FULLSCREEN | pygame.SCALED) if fullscreen else pygame.SCALED
                    screen = pygame.display.set_mode((SCREEN_W, SCREEN_H), flag)

            elif event.type == pygame.MOUSEBUTTONDOWN:
                mx, my = event.pos
                mods = pygame.key.get_mods()
                if event.button == 1:
                    if mods & pygame.KMOD_SHIFT:
                        r = RADIUS_MEDIUM
                    elif mods & pygame.KMOD_CTRL:
                        r = RADIUS_SMALL
                    else:
                        r = RADIUS_LARGE
                    points.append((mx, my, r))
                elif event.button == 3:
                    idx = _nearest(points, mx, my)
                    if idx is not None:
                        points.pop(idx)

        # ── Draw ──────────────────────────────────────────────────────────────
        screen.blit(bg, (0, 0))

        # Semi-transparent preview halos
        for x, y, r in points:
            c = RADIUS_COLORS[r]
            # Halo preview
            preview = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
            pygame.draw.circle(preview, (*c, 50), (r, r), r)
            screen.blit(preview, (x - r, y - r))
            # Crosshair
            pygame.draw.line(screen, c, (x - 10, y), (x + 10, y), 1)
            pygame.draw.line(screen, c, (x, y - 10), (x, y + 10), 1)
            pygame.draw.circle(screen, c, (x, y), 3)
            pygame.draw.circle(screen, c, (x, y), r, 1)

        # Legend
        legend = [
            ("Left Click = Large  (r=45)", COLOR_LARGE),
            ("Shift+Click = Medium (r=28)", COLOR_MEDIUM),
            ("Ctrl+Click  = Small  (r=18)", COLOR_SMALL),
            ("Right Click = Remove | Z=Undo | S=Save | F=Fullscreen | ESC=Quit", (200, 200, 200)),
        ]
        for i, (txt, col) in enumerate(legend):
            surf = font.render(txt, True, col)
            screen.blit(surf, (8, 8 + i * 18))

        count_surf = font.render(f"Points: {len(points)}", True, (255, 255, 255))
        screen.blit(count_surf, (SCREEN_W - 120, 8))

        pygame.display.flip()
        clock.tick(60)

    if points:
        _save(points)
    pygame.quit()


if __name__ == "__main__":
    main()
