"""
Halo Calibration Tool
=====================
Usage: python3 scripts/calibrate_halos.py

Press M to switch between FIRE mode (lanternes) and MUSHROOM mode.

FIRE mode:
  Left Click   → Large fire halo (r=45)
  Shift+Click  → Medium fire halo (r=28)
  Ctrl+Click   → Small fire halo (r=18)

MUSHROOM mode:
  Left Click   → Cyan mushroom glow (r=22)
  Shift+Click  → Red mushroom glow (r=16)
  Ctrl+Click   → Tiny cyan glow (r=11)

Both modes:
  Right Click  → Remove nearest halo (any list)
  Z            → Undo last added halo (current mode)
  S            → Save BACKGROUND_LIGHTS + MUSHROOM_LIGHTS
  F            → Toggle fullscreen/windowed
  Q / ESC      → Quit (auto-saves)
"""

import math
import os
import sys

import pygame

BG_PATH = os.path.join("assets", "images", "menu", "01-menu_background.png")
OUTPUT_PATH = os.path.join("scripts", "calibration_result.py")
SCREEN_W, SCREEN_H = 1280, 720

# ── Fire halos ────────────────────────────────────────────────────────────────
R_FIRE_L, R_FIRE_M, R_FIRE_S = 45, 28, 18
FIRE_COLORS = {
    R_FIRE_L: (255, 60, 60),
    R_FIRE_M: (255, 160, 30),
    R_FIRE_S: (255, 240, 60),
}
FIRE_LABELS = {R_FIRE_L: "lanterne", R_FIRE_M: "fenêtre", R_FIRE_S: "petite fenêtre"}

# ── Mushroom halos ────────────────────────────────────────────────────────────
R_MUSH_L, R_MUSH_M, R_MUSH_S = 22, 16, 11
MUSH_CYAN = (70, 220, 200)
MUSH_RED = (220, 80, 60)
MUSH_COLORS = {
    R_MUSH_L: MUSH_CYAN,
    R_MUSH_M: MUSH_RED,
    R_MUSH_S: MUSH_CYAN,
}
MUSH_LABELS = {R_MUSH_L: "cyan large", R_MUSH_M: "rouge", R_MUSH_S: "cyan petit"}

MODE_FIRE, MODE_MUSH = "FIRE", "MUSHROOM"


def _nearest(all_points: list, mx: int, my: int, threshold: int = 35) -> int | None:
    best_i, best_d = None, float(threshold)
    for i, pt in enumerate(all_points):
        d = math.hypot(pt[0] - mx, pt[1] - my)
        if d < best_d:
            best_i, best_d = i, d
    return best_i


def _save(fire: list, mush: list) -> None:
    lines = ["# Generated by scripts/calibrate_halos.py\n", "BACKGROUND_LIGHTS = [\n"]
    for x, y, r in fire:
        lines.append(f"    ({x:4d}, {y:4d}, {r:2d}),  # {FIRE_LABELS.get(r, 'halo')}\n")
    lines.append("]\n\n")

    lines.append("MUSHROOM_LIGHTS = [\n")
    for x, y, r, color in mush:
        lines.append(
            f"    ({x:4d}, {y:4d}, {r:2d}, ({color[0]:3d}, {color[1]:3d}, {color[2]:3d})),"
            f"  # {MUSH_LABELS.get(r, 'champignon')}\n"
        )
    lines.append("]\n")

    with open(OUTPUT_PATH, "w") as f:
        f.writelines(lines)
    print(f"→ Saved {len(fire)} fire + {len(mush)} mushroom halos to {OUTPUT_PATH}")  # noqa


def _draw_legend(
    screen: pygame.Surface, font: pygame.Font, mode: str, n_fire: int, n_mush: int
) -> None:
    if mode == MODE_FIRE:
        lines = [
            ("[ MODE: FIRE ]  M=switch to MUSHROOM", (255, 200, 80)),
            ("Left=Large(45)  Shift=Medium(28)  Ctrl=Small(18)", FIRE_COLORS[R_FIRE_L]),
        ]
    else:
        lines = [
            ("[ MODE: MUSHROOM ]  M=switch to FIRE", (80, 240, 210)),
            ("Left=Cyan(22)  Shift=Red(16)  Ctrl=Tiny(11)", MUSH_CYAN),
        ]
    lines += [
        ("Right=Remove  Z=Undo  S=Save  F=Fullscreen  ESC=Quit", (200, 200, 200)),
        (f"Fire: {n_fire}  Mushrooms: {n_mush}", (255, 255, 255)),
    ]
    for i, (txt, col) in enumerate(lines):
        screen.blit(font.render(txt, True, col), (8, 8 + i * 18))


def _draw_points(screen: pygame.Surface, fire: list, mush: list) -> None:
    for x, y, r in fire:
        c = FIRE_COLORS.get(r, (255, 255, 255))
        preview = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
        pygame.draw.circle(preview, (*c, 50), (r, r), r)
        screen.blit(preview, (x - r, y - r))
        pygame.draw.line(screen, c, (x - 10, y), (x + 10, y), 1)
        pygame.draw.line(screen, c, (x, y - 10), (x, y + 10), 1)
        pygame.draw.circle(screen, c, (x, y), 3)
        pygame.draw.circle(screen, c, (x, y), r, 1)

    for x, y, r, color in mush:
        preview = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
        pygame.draw.circle(preview, (*color, 70), (r, r), r)
        screen.blit(preview, (x - r, y - r))
        pygame.draw.line(screen, color, (x - 8, y), (x + 8, y), 1)
        pygame.draw.line(screen, color, (x, y - 8), (x, y + 8), 1)
        pygame.draw.circle(screen, color, (x, y), 3)
        pygame.draw.circle(screen, color, (x, y), r, 1)


def main() -> None:
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_W, SCREEN_H), pygame.FULLSCREEN | pygame.SCALED)
    pygame.display.set_caption("Halo Calibration")

    try:
        bg = pygame.image.load(BG_PATH).convert()
        bg = pygame.transform.smoothscale(bg, (SCREEN_W, SCREEN_H))
    except pygame.error as e:
        print(f"Cannot load background: {e}")  # noqa
        sys.exit(1)

    font = pygame.font.SysFont("monospace", 14)
    fire_pts: list[tuple[int, int, int]] = []
    mush_pts: list[tuple[int, int, int, tuple]] = []
    mode = MODE_FIRE
    clock = pygame.time.Clock()

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_ESCAPE, pygame.K_q):
                    running = False
                elif event.key == pygame.K_m:
                    mode = MODE_MUSH if mode == MODE_FIRE else MODE_FIRE
                elif event.key == pygame.K_z:
                    if mode == MODE_FIRE and fire_pts:
                        fire_pts.pop()
                    elif mode == MODE_MUSH and mush_pts:
                        mush_pts.pop()
                elif event.key == pygame.K_s:
                    _save(fire_pts, mush_pts)
                elif event.key == pygame.K_f:
                    flag = pygame.FULLSCREEN | pygame.SCALED
                    screen = pygame.display.set_mode((SCREEN_W, SCREEN_H), flag)

            elif event.type == pygame.MOUSEBUTTONDOWN:
                mx, my = event.pos
                mods = pygame.key.get_mods()
                if event.button == 1:
                    if mode == MODE_FIRE:
                        r = (
                            R_FIRE_M
                            if mods & pygame.KMOD_SHIFT
                            else (R_FIRE_S if mods & pygame.KMOD_CTRL else R_FIRE_L)
                        )
                        fire_pts.append((mx, my, r))
                    else:
                        r = (
                            R_MUSH_M
                            if mods & pygame.KMOD_SHIFT
                            else (R_MUSH_S if mods & pygame.KMOD_CTRL else R_MUSH_L)
                        )
                        mush_pts.append((mx, my, r, MUSH_COLORS[r]))
                elif event.button == 3:
                    # Remove from whichever list has the nearest point
                    idx = _nearest([(x, y, 0) for x, y, *_ in fire_pts + mush_pts], mx, my)
                    if idx is not None:
                        if idx < len(fire_pts):
                            fire_pts.pop(idx)
                        else:
                            mush_pts.pop(idx - len(fire_pts))

        screen.blit(bg, (0, 0))
        _draw_points(screen, fire_pts, mush_pts)
        _draw_legend(screen, font, mode, len(fire_pts), len(mush_pts))
        pygame.display.flip()
        clock.tick(60)

    if fire_pts or mush_pts:
        _save(fire_pts, mush_pts)
    pygame.quit()


if __name__ == "__main__":
    main()
