#!/usr/bin/env python3
"""Spec↔Test Traceability Report.

Cross-references TC IDs from docs/specs/ with @pytest.mark.tc decorators
in the test suite to produce a coverage report.

Usage:
    python scripts/tc_report.py              # CLI report
    python scripts/tc_report.py --markdown   # + export docs/traceability.md
"""
import argparse
import glob
import os
import re
import subprocess
import sys
from collections import defaultdict


SPECS_DIR = "docs/specs"
TRACEABILITY_OUTPUT = "docs/traceability.md"


def extract_spec_tc_ids(specs_dir: str) -> dict[str, list[str]]:
    """Parse specs to extract TC-ID → spec name mappings."""
    tc_to_spec = {}
    spec_tcs = defaultdict(list)

    for spec in sorted(glob.glob(f"{specs_dir}/*.md")):
        with open(spec) as f:
            content = f.read()
        name = os.path.basename(spec)
        for tc_id, func_name in re.findall(
            r"\|\s*([\w-]+)\s*\|\s*`(test_[^`]+)`\s*\|\s*`\.\./\.\./[^`]+`",
            content,
        ):
            tc_to_spec[tc_id] = name
            spec_tcs[name].append(tc_id)

    return tc_to_spec, spec_tcs


def extract_pytest_tc_markers() -> dict[str, list[str]]:
    """Run pytest --collect-only to extract tc markers from tests."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-header"],
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )

    # Parse test node IDs to find tc markers — we need verbose output
    result_verbose = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-m", "tc"],
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )

    # Fall back to source scanning for tc markers
    return _scan_source_for_markers()


def _scan_source_for_markers() -> dict[str, list[str]]:
    """Scan test source files for @pytest.mark.tc decorators."""
    tc_to_tests = defaultdict(list)
    test_dir = "tests"

    for test_file in sorted(glob.glob(f"{test_dir}/**/*.py", recursive=True)):
        if "__pycache__" in test_file:
            continue
        with open(test_file) as f:
            lines = f.readlines()

        pending_tcs = []
        for line in lines:
            tc_match = re.search(r'@pytest\.mark\.tc\("([\w-]+)"\)', line)
            if tc_match:
                pending_tcs.append(tc_match.group(1))
            elif re.match(r"\s*def (test_\w+)\(", line) and pending_tcs:
                func_match = re.match(r"\s*def (test_\w+)\(", line)
                func_name = func_match.group(1)
                node_id = f"{test_file}::{func_name}"
                for tc_id in pending_tcs:
                    tc_to_tests[tc_id].append(node_id)
                pending_tcs = []
            elif not line.strip().startswith("@"):
                pending_tcs = []

    return tc_to_tests


def generate_report(
    tc_to_spec: dict,
    spec_tcs: dict,
    tc_to_tests: dict,
    markdown: bool = False,
) -> None:
    """Generate and print the traceability report."""
    all_spec_ids = set(tc_to_spec.keys())
    all_test_ids = set(tc_to_tests.keys())

    covered = all_spec_ids & all_test_ids
    missing = all_spec_ids - all_test_ids
    orphans = all_test_ids - all_spec_ids

    coverage_pct = (len(covered) / len(all_spec_ids) * 100) if all_spec_ids else 0

    print("SPEC↔TEST TRACEABILITY REPORT")
    print("=" * 40)
    print(f"Specs scanned:      {len(spec_tcs)}")
    print(f"TC IDs in specs:    {len(all_spec_ids)}")
    print(f"TC markers found:   {len(all_test_ids)}")
    print(f"Coverage:           {coverage_pct:.0f}% ({len(covered)}/{len(all_spec_ids)})")
    print(f"Missing markers:    {len(missing)}")
    print(f"Orphan markers:     {len(orphans)}")

    if missing:
        print(f"\n❌ MISSING (in spec but no @pytest.mark.tc):")
        for tc_id in sorted(missing):
            print(f"   {tc_id} — {tc_to_spec[tc_id]}")

    if orphans:
        print(f"\n⚠️  ORPHAN (in test but not in spec):")
        for tc_id in sorted(orphans):
            tests = tc_to_tests[tc_id]
            print(f"   {tc_id} — {tests[0]}")

    if not missing and not orphans:
        print("\n✅ Perfect alignment — every spec TC has a marker, no orphans.")

    if markdown:
        _write_markdown(tc_to_spec, spec_tcs, tc_to_tests, covered, missing, orphans)


def _write_markdown(
    tc_to_spec: dict,
    spec_tcs: dict,
    tc_to_tests: dict,
    covered: set,
    missing: set,
    orphans: set,
) -> None:
    """Export a markdown traceability matrix."""
    lines = [
        "<!-- Auto-generated by scripts/tc_report.py -->",
        "",
        "# Spec↔Test Traceability Matrix",
        "",
        f"**Coverage:** {len(covered)}/{len(tc_to_spec)} "
        f"({len(covered)/len(tc_to_spec)*100:.0f}%)",
        "",
    ]

    for spec_name in sorted(spec_tcs.keys()):
        tcs = spec_tcs[spec_name]
        if not tcs:
            continue
        lines.append(f"## {spec_name}")
        lines.append("")
        lines.append("| TC ID | Status | Test |")
        lines.append("|-------|--------|------|")
        for tc_id in tcs:
            if tc_id in covered:
                test_nodes = tc_to_tests[tc_id]
                lines.append(f"| {tc_id} | ✅ | `{test_nodes[0]}` |")
            else:
                lines.append(f"| {tc_id} | ❌ MISSING | — |")
        lines.append("")

    if orphans:
        lines.append("## Orphan Markers (no spec)")
        lines.append("")
        lines.append("| TC ID | Test |")
        lines.append("|-------|------|")
        for tc_id in sorted(orphans):
            lines.append(f"| {tc_id} | `{tc_to_tests[tc_id][0]}` |")
        lines.append("")

    with open(TRACEABILITY_OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n📄 Exported: {TRACEABILITY_OUTPUT}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Spec↔Test Traceability Report")
    parser.add_argument(
        "--markdown", action="store_true", help="Export docs/traceability.md"
    )
    args = parser.parse_args()

    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    tc_to_spec, spec_tcs = extract_spec_tc_ids(SPECS_DIR)
    tc_to_tests = _scan_source_for_markers()
    generate_report(tc_to_spec, spec_tcs, tc_to_tests, markdown=args.markdown)


if __name__ == "__main__":
    main()
